name: ⚡ Bulk Issue Deletor 

on:
  workflow_dispatch:
    inputs:
      issue_count_begin:
        description: 'Issue Count Beginning from.'
        required: true
        default: '27000'
      issue_count_end:
        description: 'Issue Count Ending to.'
        required: true
        default: '27001'

jobs:
  job:
    runs-on: ubuntu-latest
    name: Delete Job
    steps:
      - name: Install GitHub CLI
        run: |
          sudo apt-get install gh -y

      - uses: actions/checkout@v4
      - name: Create Issues
        run: |
          for i in $(seq ${{ github.event.inputs.issue_count_begin }} ${{ github.event.inputs.issue_count_end }}); do
            sleep 3
            gh issue delete $i --yes
            echo "Issue #$i closed."
          done
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}